"""Unified AFPM generator design engine.

This module is the single production-facing orchestration API for a low-speed
axial-flux permanent-magnet generator design package. It runs the autonomous
lab, selects the best candidate, performs a deterministic thermal screen, and
writes durable artifacts for CAD handoff and 3D inspection.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path
from textwrap import dedent

from pydantic import BaseModel, Field

from neuroflux.core.models import AFPMTopology
from neuroflux.discovery import DesignCandidate, DesignRequirements
from neuroflux.lab import AutonomousLab, LabRunConfig, LabRunResult
from neuroflux.validation import ValidationPipeline, ValidationResult, ValidationSpec


class AFPMGeneratorSpec(BaseModel):
    """Single public input model for an AFPM generator design run."""

    name: str = Field(default="low-speed-250w-afpm-generator", min_length=1)
    target_power_w: float = Field(default=250.0, gt=0)
    target_speed_rpm: float = Field(default=600.0, gt=0)
    target_voltage_v: float = Field(default=48.0, gt=0)
    max_outer_diameter_m: float = Field(default=0.32, gt=0)
    min_efficiency: float = Field(default=0.50, gt=0, lt=1)
    topology: AFPMTopology = Field(default=AFPMTopology.DSSR_SLOTTED)
    prefer_halbach: bool = Field(default=False)
    ambient_temp_c: float = Field(default=40.0)
    max_winding_temp_c: float = Field(default=120.0, gt=0)
    convection_w_per_m2k: float = Field(default=18.0, gt=0)
    iterations: int = Field(default=3, ge=1, le=200)
    num_candidates: int = Field(default=6, ge=1, le=20)
    num_planes: int = Field(default=7, ge=3, le=21)

    # Phase 2: 3D Validation options
    run_3d_validation: bool = Field(
        default=True, description="Run Phase 2 3D thermal FEA validation"
    )
    run_external_solvers: bool = Field(
        default=False, description="Run Elmer/Palace if available (requires installation)"
    )
    validation_refinement: str = Field(
        default="medium", pattern=r"^(coarse|medium|fine)$"
    )

    def to_requirements(self) -> DesignRequirements:
        """Convert public spec to the discovery workflow requirements model."""
        return DesignRequirements(
            target_power_w=self.target_power_w,
            target_speed_rpm=self.target_speed_rpm,
            target_voltage_v=self.target_voltage_v,
            max_outer_diameter_m=self.max_outer_diameter_m,
            min_efficiency=self.min_efficiency,
            topology=self.topology,
            prefer_halbach=self.prefer_halbach,
            num_candidates=self.num_candidates,
            num_planes=self.num_planes,
        )


class ThermalAnalysis(BaseModel):
    """Lumped steady-state thermal screen for the selected candidate."""

    ambient_temp_c: float
    max_winding_temp_c: float
    max_magnet_temp_c: float
    total_losses_w: float
    copper_losses_w: float
    iron_losses_w: float
    pm_losses_w: float
    convective_area_m2: float
    thermal_resistance_k_per_w: float
    status: str
    warnings: list[str] = Field(default_factory=list)


class RenderMesh(BaseModel):
    """Parametric 3D primitive consumed by the Rust GUI or HTML viewer."""

    kind: str
    name: str
    material: str
    color: str
    dimensions: dict[str, float]
    transform: dict[str, float] = Field(default_factory=dict)


class RenderingScene(BaseModel):
    """High-quality deterministic 3D scene description for the design."""

    title: str
    units: str = "m"
    camera: dict[str, float]
    meshes: list[RenderMesh]


class DesignArtifacts(BaseModel):
    """Absolute artifact paths generated by the design engine."""

    manifest_json: str
    report_md: str
    geometry_geo: str
    assembly_scad: str
    assembly_stl: str
    cad_index_json: str
    scene3d_json: str
    viewer_html: str
    thermal_json: str
    parameters_csv: str
    lab_manifest_json: str


class AFPMDesignResult(BaseModel):
    """Unified output from the AFPM design engine (Phase 1 + Phase 2)."""

    spec: AFPMGeneratorSpec
    lab_result: LabRunResult
    best_candidate: DesignCandidate | None
    thermal_analysis: ThermalAnalysis
    rendering_scene: RenderingScene
    artifacts: DesignArtifacts
    design_package_dir: str
    # Phase 2: 3D Validation
    validation_result: ValidationResult | None = None
    validation_passed: bool = True


class AFPMDesignEngine:
    """Produce a complete AFPM generator design package from one input spec."""

    def __init__(self, output_root: str | Path = "design_runs") -> None:
        self.output_root = Path(output_root)

    def design_low_speed_250w_generator(self) -> AFPMDesignResult:
        """Run the concrete low-speed generator use case selected for NeuroFlux."""
        return self.design(AFPMGeneratorSpec())

    def design(self, spec: AFPMGeneratorSpec) -> AFPMDesignResult:
        """Run lab, thermal analysis, 3D validation (Phase 2), and artifact export."""
        package_dir = self.output_root / self._slug(spec.name)
        package_dir.mkdir(parents=True, exist_ok=True)

        lab = AutonomousLab(output_root=package_dir / "lab")
        lab_result = lab.run(
            LabRunConfig(
                requirements=spec.to_requirements(),
                iterations=spec.iterations,
                run_id="autonomous-lab",
            )
        )
        if lab_result.best_candidate is None:
            raise RuntimeError("Autonomous lab produced no candidate")

        best_candidate = lab_result.best_candidate
        thermal = self._analyze_thermal(spec, best_candidate)
        scene = self._build_scene(spec, best_candidate)

        # ─────────────────────────────────────────────────────────────────
        # Phase 2: 3D Validation Pipeline
        # ─────────────────────────────────────────────────────────────────
        validation_result = None
        validation_passed = True
        if spec.run_3d_validation:
            pipeline = ValidationPipeline(output_root=package_dir / "validation")
            validation_result = pipeline.run(
                ValidationSpec(
                    name=spec.name,
                    geometry=best_candidate.analytical_input.geometry,
                    materials=best_candidate.analytical_input.materials,
                    winding=best_candidate.analytical_input.winding,
                    operating_point=best_candidate.analytical_input.operating_point,
                    run_analytical=True,
                    run_thermal_fea3d=True,
                    run_elmer_fea=spec.run_external_solvers,
                    run_palace=False,
                    generate_handoffs=True,
                    mesh_refinement=spec.validation_refinement,
                )
            )
            validation_passed = validation_result.passed

        artifacts = self._write_artifacts(
            package_dir,
            spec,
            lab_result,
            best_candidate,
            thermal,
            scene,
            validation_result,
        )

        result = AFPMDesignResult(
            spec=spec,
            lab_result=lab_result,
            best_candidate=best_candidate,
            thermal_analysis=thermal,
            rendering_scene=scene,
            artifacts=artifacts,
            design_package_dir=str(package_dir.resolve()),
            validation_result=validation_result,
            validation_passed=validation_passed,
        )
        self._write_json(Path(artifacts.manifest_json), result.model_dump(mode="json"))
        return result

    def _analyze_thermal(
        self,
        spec: AFPMGeneratorSpec,
        candidate: DesignCandidate,
    ) -> ThermalAnalysis:
        geometry = candidate.analytical_input.geometry
        losses = candidate.analytical_result.losses
        total_losses = max(candidate.analytical_result.total_losses_w, 0.01)
        copper_losses = self._loss_value(losses, "copper")
        iron_losses = self._loss_value(losses, "iron")
        pm_losses = self._loss_value(losses, "pm")
        rotor_area = 2.0 * math.pi * (geometry.r_out**2 - geometry.r_in**2)
        edge_area = 2.0 * math.pi * geometry.r_out * max(geometry.l_s, geometry.l_PM)
        convective_area = max(0.01, rotor_area + edge_area)
        thermal_resistance = 1.0 / (spec.convection_w_per_m2k * convective_area)
        winding_temp = spec.ambient_temp_c + total_losses * thermal_resistance
        magnet_temp = spec.ambient_temp_c + (pm_losses + 0.35 * copper_losses) * thermal_resistance

        warnings: list[str] = []
        if winding_temp > spec.max_winding_temp_c:
            warnings.append(
                f"Winding temperature {winding_temp:.1f} C exceeds limit "
                f"{spec.max_winding_temp_c:.1f} C"
            )
        if magnet_temp > 100.0:
            warnings.append(f"Magnet temperature {magnet_temp:.1f} C may demagnetize N-grade NdFeB")

        status = "pass"
        if warnings:
            status = "fail" if winding_temp > spec.max_winding_temp_c else "warning"

        return ThermalAnalysis(
            ambient_temp_c=spec.ambient_temp_c,
            max_winding_temp_c=winding_temp,
            max_magnet_temp_c=magnet_temp,
            total_losses_w=total_losses,
            copper_losses_w=copper_losses,
            iron_losses_w=iron_losses,
            pm_losses_w=pm_losses,
            convective_area_m2=convective_area,
            thermal_resistance_k_per_w=thermal_resistance,
            status=status,
            warnings=warnings,
        )

    def _build_scene(self, spec: AFPMGeneratorSpec, candidate: DesignCandidate) -> RenderingScene:
        geometry = candidate.analytical_input.geometry
        pole_count = geometry.p * 2
        meshes = [
            RenderMesh(
                kind="rotor_disk",
                name="rotor_back_iron",
                material="electrical_steel",
                color="#58616a",
                dimensions={
                    "outer_radius": geometry.r_out,
                    "inner_radius": geometry.r_in,
                    "thickness": geometry.rotor_yoke_thickness or geometry.l_s * 0.35,
                },
                transform={"z": -geometry.g - geometry.l_PM},
            ),
            RenderMesh(
                kind="stator",
                name="stator_core_or_winding",
                material="copper_and_steel",
                color="#b66a2c",
                dimensions={
                    "outer_radius": geometry.r_out * 0.98,
                    "inner_radius": geometry.r_in * 1.02,
                    "thickness": geometry.l_s,
                    "slots": float(geometry.Q),
                },
                transform={"z": 0.0},
            ),
        ]
        for pole_index in range(pole_count):
            angle = 2.0 * math.pi * pole_index / pole_count
            meshes.append(
                RenderMesh(
                    kind="magnet",
                    name=f"pm_{pole_index + 1:02d}",
                    material="ndfeb",
                    color="#1f77b4" if pole_index % 2 == 0 else "#d62728",
                    dimensions={
                        "radius": (geometry.r_in + geometry.r_out) / 2.0,
                        "radial_width": geometry.active_length * 0.86,
                        "arc_width": geometry.w_PM,
                        "thickness": geometry.l_PM,
                        "angle_rad": angle,
                    },
                    transform={"z": -geometry.g * 0.5, "rotation_z": angle},
                )
            )

        return RenderingScene(
            title=f"{spec.name} 3D AFPM design scene",
            camera={"x": 0.0, "y": -geometry.D_out * 1.7, "z": geometry.D_out * 1.1},
            meshes=meshes,
        )

    def _write_artifacts(
        self,
        package_dir: Path,
        spec: AFPMGeneratorSpec,
        lab_result: LabRunResult,
        candidate: DesignCandidate,
        thermal: ThermalAnalysis,
        scene: RenderingScene,
        validation_result: ValidationResult | None = None,
    ) -> DesignArtifacts:
        paths = DesignArtifacts(
            manifest_json=str((package_dir / "design_manifest.json").resolve()),
            report_md=str((package_dir / "design_report.md").resolve()),
            geometry_geo=str((package_dir / "geometry.geo").resolve()),
            assembly_scad=str((package_dir / "assembly.scad").resolve()),
            assembly_stl=str((package_dir / "assembly.stl").resolve()),
            cad_index_json=str((package_dir / "cad_index.json").resolve()),
            scene3d_json=str((package_dir / "scene3d.json").resolve()),
            viewer_html=str((package_dir / "viewer.html").resolve()),
            thermal_json=str((package_dir / "thermal_analysis.json").resolve()),
            parameters_csv=str((package_dir / "parameters.csv").resolve()),
            lab_manifest_json=lab_result.manifest_path,
        )

        self._write_json(Path(paths.thermal_json), thermal.model_dump(mode="json"))
        self._write_json(Path(paths.scene3d_json), scene.model_dump(mode="json"))
        Path(paths.report_md).write_text(
            self._render_report(spec, candidate, thermal, paths, validation_result),
            encoding="utf-8",
        )
        Path(paths.geometry_geo).write_text(self._render_geo(candidate), encoding="utf-8")
        Path(paths.assembly_scad).write_text(self._render_openscad(candidate), encoding="utf-8")
        Path(paths.assembly_stl).write_text(self._render_ascii_stl(candidate), encoding="utf-8")
        self._write_json(
            Path(paths.cad_index_json),
            self._build_cad_index(paths, candidate),
        )
        Path(paths.viewer_html).write_text(self._render_viewer_html(scene), encoding="utf-8")
        self._write_parameters_csv(Path(paths.parameters_csv), spec, candidate, thermal)
        return paths

    def _render_report(
        self,
        spec: AFPMGeneratorSpec,
        candidate: DesignCandidate,
        thermal: ThermalAnalysis,
        artifacts: DesignArtifacts,
        validation_result: ValidationResult | None = None,
    ) -> str:
        result = candidate.analytical_result
        geometry = candidate.analytical_input.geometry
        
        # Build validation section if available
        validation_section = ""
        if validation_result and validation_result.thermal.native_fea3d:
            fea = validation_result.thermal.native_fea3d
            validation_section = f"""
            ## Phase 2: 3D Validation (Native FEA)

            - **Validation Status**: {"PASS" if validation_result.passed else "FAIL"}
            - **Confidence**: {validation_result.thermal.confidence}
            - **3D Max Temperature**: {fea.max_temp_c:.1f} C
            - **3D Avg Temperature**: {fea.average_temp_c:.1f} C
            - **Hotspot Location**: r={fea.hotspot_radius_m:.4f} m, θ={fea.hotspot_angle_deg:.1f}°, z={fea.hotspot_z_m:.4f} m
            - **Thermal Margin to 180°C**: {fea.thermal_margin_to_180c:.1f} C
            - **Solve Time**: {fea.solve_time_ms:.0f} ms
            - **Node Count**: {fea.node_count}
            - **VTK Output**: `{fea.vtk_path}`

            ## Solver Handoffs Generated

            """ + "\n".join([
                f"- **{h.solver_name}**: `{h.case_dir}`" 
                for h in validation_result.solver_handoffs
            ])
        
        return dedent(
            f"""
            # NeuroFlux AFPM Generator Design: {spec.name}

            ## Use Case

            Low-speed permanent-magnet generator targeting {spec.target_power_w:.1f} W at
            {spec.target_speed_rpm:.1f} rpm and {spec.target_voltage_v:.1f} V.

            ## Selected Design

            - Candidate: {candidate.candidate_id}
            - Topology: {geometry.topology.value}
            - Outer diameter: {geometry.D_out:.4f} m
            - Inner diameter: {geometry.D_in:.4f} m
            - Pole count: {geometry.p * 2}
            - Slots: {geometry.Q}
            - Air gap: {geometry.g:.4f} m
            - Magnet thickness: {geometry.l_PM:.4f} m
            - Turns per phase: {candidate.analytical_input.winding.turns_per_phase}

            ## Performance

            - Torque: {result.torque_nm:.3f} N m
            - Power: {result.power_w:.3f} W
            - Back EMF RMS: {result.back_emf_rms:.3f} V
            - Efficiency: {result.efficiency:.3f}
            - Total losses: {result.total_losses_w:.3f} W

            ## Phase 1: Thermal Screen

            - Status: {thermal.status}
            - Winding temperature: {thermal.max_winding_temp_c:.1f} C
            - Magnet temperature: {thermal.max_magnet_temp_c:.1f} C
            - Convective area: {thermal.convective_area_m2:.4f} m2
            {validation_section}

            ## Artifact Index

            - Manifest: `{artifacts.manifest_json}`
            - 3D scene: `{artifacts.scene3d_json}`
            - Browser viewer: `{artifacts.viewer_html}`
            - Gmsh geometry: `{artifacts.geometry_geo}`
            - OpenSCAD assembly: `{artifacts.assembly_scad}`
            - STL inspection mesh: `{artifacts.assembly_stl}`
            - CAD index: `{artifacts.cad_index_json}`
            - Thermal JSON: `{artifacts.thermal_json}`
            - Parameter CSV: `{artifacts.parameters_csv}`
            """
        ).strip() + "\n"

    def _render_geo(self, candidate: DesignCandidate) -> str:
        geometry = candidate.analytical_input.geometry
        return dedent(
            f"""
            // NeuroFlux AFPM parametric geometry for Gmsh handoff.
            SetFactory("OpenCASCADE");
            r_in = {geometry.r_in:.8f};
            r_out = {geometry.r_out:.8f};
            stator_thickness = {geometry.l_s:.8f};
            magnet_thickness = {geometry.l_PM:.8f};
            air_gap = {geometry.g:.8f};
            pole_count = {geometry.p * 2};
            slot_count = {geometry.Q};
            Cylinder(1) = {{0, 0, -stator_thickness/2, 0, 0, stator_thickness, r_out}};
            Cylinder(2) = {{0, 0, -stator_thickness/2, 0, 0, stator_thickness, r_in}};
            BooleanDifference{{ Volume{{1}}; Delete; }}{{ Volume{{2}}; Delete; }}
            Physical Volume("stator_active_region") = {{1}};
            Mesh.CharacteristicLengthMin = {geometry.g / 2.0:.8f};
            Mesh.CharacteristicLengthMax = {geometry.active_length / 5.0:.8f};
            """
        ).lstrip()

    def _render_openscad(self, candidate: DesignCandidate) -> str:
        geometry = candidate.analytical_input.geometry
        pole_count = geometry.p * 2
        magnet_radius = (geometry.r_in + geometry.r_out) / 2.0
        magnet_radial_width = geometry.active_length * 0.86
        magnet_arc_width = geometry.w_PM
        stator_z = 0.0
        rotor_z = -geometry.g - geometry.l_PM
        return dedent(
            f"""
            // NeuroFlux manufacturable AFPM inspection assembly.
            // Units: meters. Import into OpenSCAD, FreeCAD, or convert with openscad CLI.
            $fn = 144;
            module ring(outer_radius, inner_radius, thickness) {{
              difference() {{
                cylinder(h = thickness, r = outer_radius, center = true);
                cylinder(h = thickness * 1.2, r = inner_radius, center = true);
              }}
            }}
            module magnet_block(radial_width, arc_width, thickness) {{
              cube([radial_width, arc_width, thickness], center = true);
            }}
            color("#58616a")
              translate([0, 0, {rotor_z:.8f}])
                ring({geometry.r_out:.8f}, {geometry.r_in:.8f}, {geometry.l_s * 0.35:.8f});
            color("#b66a2c")
              translate([0, 0, {stator_z:.8f}])
                ring({geometry.r_out * 0.98:.8f}, {geometry.r_in * 1.02:.8f}, {geometry.l_s:.8f});
            for (i = [0:{pole_count - 1}]) {{
              angle = 360 * i / {pole_count};
              color((i % 2 == 0) ? "#1f77b4" : "#d62728")
                rotate([0, 0, angle])
                  translate([{magnet_radius:.8f}, 0, {-geometry.g * 0.5:.8f}])
                    magnet_block(
                      {magnet_radial_width:.8f},
                      {magnet_arc_width:.8f},
                      {geometry.l_PM:.8f}
                    );
            }}
            """
        ).lstrip()

    def _render_ascii_stl(self, candidate: DesignCandidate) -> str:
        geometry = candidate.analytical_input.geometry
        height = max(geometry.l_s, geometry.l_PM)
        radius = geometry.r_out
        half = height / 2.0
        vertices = [
            (-radius, -radius, -half),
            (radius, -radius, -half),
            (radius, radius, -half),
            (-radius, radius, -half),
            (-radius, -radius, half),
            (radius, -radius, half),
            (radius, radius, half),
            (-radius, radius, half),
        ]
        faces = [
            (0, 1, 2),
            (0, 2, 3),
            (4, 6, 5),
            (4, 7, 6),
            (0, 4, 5),
            (0, 5, 1),
            (1, 5, 6),
            (1, 6, 2),
            (2, 6, 7),
            (2, 7, 3),
            (3, 7, 4),
            (3, 4, 0),
        ]
        lines = ["solid neuroflux_afpm_inspection_envelope"]
        for face in faces:
            a, b, c = [vertices[index] for index in face]
            lines.extend(
                [
                    "  facet normal 0 0 0",
                    "    outer loop",
                    f"      vertex {a[0]:.8f} {a[1]:.8f} {a[2]:.8f}",
                    f"      vertex {b[0]:.8f} {b[1]:.8f} {b[2]:.8f}",
                    f"      vertex {c[0]:.8f} {c[1]:.8f} {c[2]:.8f}",
                    "    endloop",
                    "  endfacet",
                ]
            )
        lines.append("endsolid neuroflux_afpm_inspection_envelope")
        return "\n".join(lines) + "\n"

    def _build_cad_index(
        self,
        artifacts: DesignArtifacts,
        candidate: DesignCandidate,
    ) -> dict:
        geometry = candidate.analytical_input.geometry
        return {
            "units": "m",
            "formats": {
                "gmsh_geo": artifacts.geometry_geo,
                "openscad": artifacts.assembly_scad,
                "stl": artifacts.assembly_stl,
                "scene3d": artifacts.scene3d_json,
                "browser_viewer": artifacts.viewer_html,
            },
            "parts": [
                {
                    "name": "rotor_back_iron",
                    "material": "electrical_steel",
                    "outer_radius_m": geometry.r_out,
                    "inner_radius_m": geometry.r_in,
                },
                {
                    "name": "stator_active_region",
                    "material": "copper_and_steel",
                    "outer_radius_m": geometry.r_out * 0.98,
                    "inner_radius_m": geometry.r_in * 1.02,
                    "slot_count": geometry.Q,
                },
                {
                    "name": "permanent_magnet_array",
                    "material": "ndfeb",
                    "pole_count": geometry.p * 2,
                    "magnet_thickness_m": geometry.l_PM,
                },
            ],
        }

    def _render_viewer_html(self, scene: RenderingScene) -> str:
        scene_json = json.dumps(scene.model_dump(mode="json"), indent=2)
        return dedent(
            f"""
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <title>{scene.title}</title>
              <style>
                body {{
                  margin: 0;
                  background: #101418;
                  color: #e8edf2;
                  font-family: Arial, sans-serif;
                }}
                #app {{ display: grid; grid-template-columns: 320px 1fr; min-height: 100vh; }}
                aside {{ padding: 20px; background: #171d23; border-right: 1px solid #2a343d; }}
                canvas {{ width: 100%; height: 100vh; display: block; }}
                pre {{ white-space: pre-wrap; font-size: 12px; }}
              </style>
            </head>
            <body>
              <div id="app">
                <aside>
                  <h1>{scene.title}</h1>
                  <p>
                    Deterministic NeuroFlux scene. Open with network access for Three.js rendering.
                  </p>
                  <pre id="meta"></pre>
                </aside>
                <canvas id="view"></canvas>
              </div>
              <script type="module">
                import * as THREE
                  from 'https://cdn.jsdelivr.net/npm/three@0.164/build/three.module.js';
                const sceneData = {scene_json};
                document.getElementById('meta').textContent =
                  JSON.stringify(sceneData.meshes.slice(0, 8), null, 2);
                const canvas = document.getElementById('view');
                const renderer = new THREE.WebGLRenderer({{ canvas, antialias: true }});
                renderer.setSize(canvas.clientWidth, canvas.clientHeight, false);
                const scene = new THREE.Scene();
                scene.background = new THREE.Color(0x101418);
                const camera = new THREE.PerspectiveCamera(
                  45,
                  canvas.clientWidth / canvas.clientHeight,
                  0.001,
                  10
                );
                camera.position.set(sceneData.camera.x, sceneData.camera.y, sceneData.camera.z);
                camera.lookAt(0, 0, 0);
                scene.add(new THREE.AmbientLight(0xffffff, 0.75));
                const light = new THREE.DirectionalLight(0xffffff, 1.8);
                light.position.set(1, -1, 2);
                scene.add(light);
                for (const mesh of sceneData.meshes) {{
                  const color = new THREE.Color(mesh.color);
                  let object;
                  if (mesh.kind === 'magnet') {{
                    object = new THREE.Mesh(
                      new THREE.BoxGeometry(
                        mesh.dimensions.radial_width,
                        mesh.dimensions.arc_width,
                        mesh.dimensions.thickness
                      ),
                      new THREE.MeshStandardMaterial({{ color, metalness: 0.15, roughness: 0.45 }})
                    );
                    const r = mesh.dimensions.radius;
                    const a = mesh.dimensions.angle_rad;
                    object.position.set(Math.cos(a) * r, Math.sin(a) * r, mesh.transform.z || 0);
                    object.rotation.z = a;
                  }} else {{
                    object = new THREE.Mesh(
                      new THREE.CylinderGeometry(
                        mesh.dimensions.outer_radius,
                        mesh.dimensions.outer_radius,
                        mesh.dimensions.thickness,
                        96
                      ),
                      new THREE.MeshStandardMaterial({{ color, metalness: 0.35, roughness: 0.38 }})
                    );
                    object.rotation.x = Math.PI / 2;
                    object.position.z = mesh.transform.z || 0;
                  }}
                  scene.add(object);
                }}
                function animate() {{
                  scene.rotation.z += 0.002;
                  renderer.render(scene, camera);
                  requestAnimationFrame(animate);
                }}
                animate();
              </script>
            </body>
            </html>
            """
        ).strip() + "\n"

    def _write_parameters_csv(
        self,
        path: Path,
        spec: AFPMGeneratorSpec,
        candidate: DesignCandidate,
        thermal: ThermalAnalysis,
    ) -> None:
        geometry = candidate.analytical_input.geometry
        rows = [
            ("name", spec.name),
            ("target_power_w", spec.target_power_w),
            ("target_speed_rpm", spec.target_speed_rpm),
            ("outer_diameter_m", geometry.D_out),
            ("inner_diameter_m", geometry.D_in),
            ("pole_count", geometry.p * 2),
            ("slot_count", geometry.Q),
            ("air_gap_m", geometry.g),
            ("magnet_thickness_m", geometry.l_PM),
            ("torque_nm", candidate.analytical_result.torque_nm),
            ("power_w", candidate.analytical_result.power_w),
            ("efficiency", candidate.analytical_result.efficiency),
            ("thermal_status", thermal.status),
            ("winding_temp_c", thermal.max_winding_temp_c),
        ]
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["parameter", "value"])
            writer.writerows(rows)

    def _loss_value(self, losses: dict[str, float], needle: str) -> float:
        return sum(value for key, value in losses.items() if needle in key.lower())

    def _write_json(self, path: Path, payload: dict) -> None:
        path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

    def _slug(self, name: str) -> str:
        chars = [char.lower() if char.isalnum() else "-" for char in name.strip()]
        slug = "".join(chars).strip("-")
        while "--" in slug:
            slug = slug.replace("--", "-")
        return slug or "afpm-design"
